Windows PowerShell
Copyright (C) Microsoft Corporation. Tous droits réservés.

Installez la dernière version de PowerShell pour de nouvelles fonctionnalités et améliorations ! https://aka.ms/PSWindows

PS C:\WINDOWS\system32> cd C:\Users\hpnel\Downloads\test app sport
Set-Location : Impossible de trouver un paramètre positionnel acceptant l'argument « app ».
Au caractère Ligne:1 : 1
+ cd C:\Users\hpnel\Downloads\test app sport
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\WINDOWS\system32> cd C:\Users\hpnel\Downloads\
PS C:\Users\hpnel\Downloads> cd test app sport
Set-Location : Impossible de trouver un paramètre positionnel acceptant l'argument « app ».
Au caractère Ligne:1 : 1
+ cd test app sport
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\hpnel\Downloads> cd test app sport\
Set-Location : Impossible de trouver un paramètre positionnel acceptant l'argument « app ».
Au caractère Ligne:1 : 1
+ cd test app sport\
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Set-Location], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\hpnel\Downloads> cd test_app_sport\
PS C:\Users\hpnel\Downloads\test_app_sport> git clone https://github.com/Dyoza/sport.git
Cloning into 'sport'...
remote: Enumerating objects: 51, done.
remote: Counting objects: 100% (51/51), done.
remote: Compressing objects: 100% (48/48), done.
Receiving objects:  56% (29/51)sed 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (51/51), 26.51 KiB | 3.31 MiB/s, done.
Resolving deltas: 100% (7/7), done.
PS C:\Users\hpnel\Downloads\test_app_sport> cd sport
PS C:\Users\hpnel\Downloads\test_app_sport\sport> cd backend
PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> python -m venv .venv
>> .\.venv\Scripts\Activate
>>
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend>
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> pip install -r requirements.txt
>>
Collecting fastapi==0.110.0
  Downloading fastapi-0.110.0-py3-none-any.whl (92 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 92.1/92.1 KB 1.7 MB/s eta 0:00:00
Collecting uvicorn[standard]==0.29.0
  Downloading uvicorn-0.29.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 KB ? eta 0:00:00
Collecting sqlmodel==0.0.14
  Downloading sqlmodel-0.0.14-py3-none-any.whl (25 kB)
Collecting SQLAlchemy==2.0.28
  Downloading SQLAlchemy-2.0.28-cp310-cp310-win_amd64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 7.8 MB/s eta 0:00:00
Collecting pydantic==1.10.14
  Downloading pydantic-1.10.14-cp310-cp310-win_amd64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 17.0 MB/s eta 0:00:00
Collecting python-multipart==0.0.9
  Downloading python_multipart-0.0.9-py3-none-any.whl (22 kB)
Collecting typing-extensions>=4.8.0
  Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 KB ? eta 0:00:00
Collecting starlette<0.37.0,>=0.36.3
  Downloading starlette-0.36.3-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.5/71.5 KB ? eta 0:00:00
Collecting click>=7.0
  Downloading click-8.3.0-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.3/107.3 KB ? eta 0:00:00
Collecting h11>=0.8
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Collecting websockets>=10.4
  Downloading websockets-15.0.1-cp310-cp310-win_amd64.whl (176 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.8/176.8 KB 10.4 MB/s eta 0:00:00
Collecting colorama>=0.4
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting httptools>=0.5.0
  Downloading httptools-0.7.1-cp310-cp310-win_amd64.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.2/86.2 KB ? eta 0:00:00
Collecting python-dotenv>=0.13
  Using cached python_dotenv-1.1.1-py3-none-any.whl (20 kB)
Collecting pyyaml>=5.1
  Downloading pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.6/158.6 KB 9.9 MB/s eta 0:00:00
Collecting watchfiles>=0.13
  Downloading watchfiles-1.1.1-cp310-cp310-win_amd64.whl (287 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.5/287.5 KB 17.3 MB/s eta 0:00:00
Collecting greenlet!=0.4.17
  Downloading greenlet-3.2.4-cp310-cp310-win_amd64.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.7/298.7 KB 18.0 MB/s eta 0:00:00
Collecting anyio<5,>=3.4.0
  Downloading anyio-4.11.0-py3-none-any.whl (109 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 109.1/109.1 KB ? eta 0:00:00
Collecting sniffio>=1.1
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting exceptiongroup>=1.0.2
  Downloading exceptiongroup-1.3.0-py3-none-any.whl (16 kB)
Collecting idna>=2.8
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 KB ? eta 0:00:00
Installing collected packages: websockets, typing-extensions, sniffio, pyyaml, python-multipart, python-dotenv, idna, httptools, h11, greenlet, colorama, SQLAlchemy, pydantic, exceptiongroup, click, uvicorn, sqlmodel, anyio, watchfiles, starlette, fastapi
Successfully installed SQLAlchemy-2.0.28 anyio-4.11.0 click-8.3.0 colorama-0.4.6 exceptiongroup-1.3.0 fastapi-0.110.0 greenlet-3.2.4 h11-0.16.0 httptools-0.7.1 idna-3.11 pydantic-1.10.14 python-dotenv-1.1.1 python-multipart-0.0.9 pyyaml-6.0.3 sniffio-1.3.1 sqlmodel-0.0.14 starlette-0.36.3 typing-extensions-4.15.0 uvicorn-0.29.0 watchfiles-1.1.1 websockets-15.0.1
WARNING: You are using pip version 22.0.4; however, version 25.2 is available.
You should consider upgrading via the 'C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\Scripts\python.exe -m pip install --upgrade pip' command.
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend>
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend>
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> python -m app.seed
>>
Base de données initialisée avec succès !
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> uvicorn app.main:app --reload
>>
INFO:     Will watch for changes in these directories: ['C:\\Users\\hpnel\\Downloads\\test_app_sport\\sport\\backend']
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [37988] using WatchFiles
INFO:     Started server process [24148]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:49406 - "GET /api/exercises HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in read_exercises
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in <listcomp>
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:49404 - "GET /api/workouts HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 43, in read_workouts
    return crud.list_workouts(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in list_workouts
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in <listcomp>
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:49401 - "GET /api/dashboard HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 38, in read_dashboard
    return crud.get_dashboard_summary(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 125, in get_dashboard_summary
    todays_workouts = [_build_workout(session, all_templates[0])] if all_templates else []
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:49408 - "GET /api/exercises HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in read_exercises
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 75, in <listcomp>
    return [schemas.ExerciseOut.from_orm(ex) for ex in exercises]
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:49410 - "GET /api/workouts HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 43, in read_workouts
    return crud.list_workouts(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in list_workouts
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 66, in <listcomp>
    return [_build_workout(session, template) for template in templates]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:49405 - "GET /api/calendar?month=10&year=2025 HTTP/1.1" 200 OK
INFO:     127.0.0.1:61861 - "GET /api/dashboard HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 411, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 186, in __call__
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 64, in wrapped_app
    raise exc
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\_exception_handler.py",line 53, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\routing.py", line 74, in app
    response = await func(request)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 278, inapp
    raw_response = await run_endpoint_function(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\fastapi\routing.py", line 193, inrun_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\starlette\concurrency.py", line 42, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2485, in run_sync_in_worker_thread
    return await future
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\anyio\_backends\_asyncio.py", line 976, in run
    result = context.run(func, *args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\main.py", line 38, in read_dashboard
    return crud.get_dashboard_summary(session)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 125, in get_dashboard_summary
    todays_workouts = [_build_workout(session, all_templates[0])] if all_templates else []
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\app\crud.py", line 37, in _build_workout
    exercise=schemas.ExerciseOut.from_orm(exercise),
  File "pydantic\main.py", line 574, in pydantic.main.BaseModel.from_orm
pydantic.errors.ConfigError: You must have the config attribute orm_mode=True to use from_orm
INFO:     127.0.0.1:57179 - "GET /api/calendar?month=10&year=2025 HTTP/1.1" 200 OK
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [24148]
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Program Files\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\_subprocess.py", line 78,in subprocess_started
    target(sockets=sockets)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\server.py", line 68, in serve
    with self.capture_signals():
  File "C:\Program Files\Python310\lib\contextlib.py", line 142, in __exit__
    next(self.gen)
  File "C:\Users\hpnel\Downloads\test_app_sport\sport\backend\.venv\lib\site-packages\uvicorn\server.py", line 328, in capture_signals
    signal.raise_signal(captured_signal)
KeyboardInterrupt
INFO:     Stopping reloader process [37988]
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend> ^C
(.venv) PS C:\Users\hpnel\Downloads\test_app_sport\sport\backend>
